import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/theme/app_colors.dart';
import '../../../domain/entities/account.dart';
import '../providers/account_providers.dart';

class AddAccountSheet extends ConsumerStatefulWidget {
  const AddAccountSheet({super.key});

  static Future<void> show(BuildContext context) {
    return showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (_) => const AddAccountSheet(),
    );
  }

  @override
  ConsumerState<AddAccountSheet> createState() => _AddAccountSheetState();
}

class _AddAccountSheetState extends ConsumerState<AddAccountSheet> {
  final _formKey = GlobalKey<FormState>();
  final _nameController = TextEditingController();
  final _initialBalanceController = TextEditingController();

  String _selectedType = 'bank';
  String _selectedCurrency = 'IDR';
  bool _isLoading = false;

  @override
  void dispose() {
    _nameController.dispose();
    _initialBalanceController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final newAccount = Account(
        id: '', // Generated by database default gen_random_uuid()
        name: _nameController.text.trim(),
        type: _selectedType,
        currency: _selectedCurrency,
        isActive: true,
      );

      final rawBalance = _initialBalanceController.text.replaceAll(RegExp(r'[^0-9.]'), '');
      final initialBalance = num.tryParse(rawBalance) ?? 0;

      await createAccount(ref, newAccount, initialBalance: initialBalance);

      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Account "${newAccount.name}" created successfully!'),
            backgroundColor: AppColors.primary,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to create account: $e'),
            backgroundColor: AppColors.red,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final bottomInset = MediaQuery.of(context).viewInsets.bottom;

    return Container(
      padding: EdgeInsets.fromLTRB(22, 20, 22, 20 + bottomInset),
      decoration: const BoxDecoration(
        color: AppColors.darkCardBg,
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
        border: Border(
          top: BorderSide(color: AppColors.darkCardBorder, width: 1.5),
        ),
      ),
      child: Form(
        key: _formKey,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Drag handle
            Center(
              child: Container(
                width: 40,
                height: 4,
                decoration: BoxDecoration(
                  color: AppColors.darkTextMuted,
                  borderRadius: BorderRadius.circular(2),
                ),
              ),
            ),
            const SizedBox(height: 18),

            // Header Title
            const Text(
              'Add New Account',
              style: TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.w700,
                color: AppColors.darkTextPrimary,
              ),
            ),
            const SizedBox(height: 6),
            const Text(
              'Funding source for balance tracking (Bank, E-Wallet, or Cash)',
              style: TextStyle(
                fontSize: 12,
                color: AppColors.darkTextSecondary,
              ),
            ),
            const SizedBox(height: 20),

            // Account Name Field
            TextFormField(
              controller: _nameController,
              style: const TextStyle(color: AppColors.darkTextPrimary, fontSize: 14),
              decoration: InputDecoration(
                labelText: 'Account Name',
                hintText: 'e.g., Chase Bank, Maybank, PayPal, Cash Wallet',
                labelStyle: const TextStyle(color: AppColors.darkTextSecondary),
                hintStyle: const TextStyle(color: AppColors.darkTextMuted, fontSize: 12),
                filled: true,
                fillColor: Colors.black45,
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(14),
                  borderSide: const BorderSide(color: AppColors.darkCardBorder),
                ),
                focusedBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(14),
                  borderSide: const BorderSide(color: AppColors.primary, width: 1.5),
                ),
              ),
              validator: (v) =>
                  (v == null || v.trim().isEmpty) ? 'Account name is required' : null,
            ),
            const SizedBox(height: 16),

            // Account Type Selector
            const Text(
              'Account Type',
              style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: AppColors.darkTextSecondary),
            ),
            const SizedBox(height: 8),
            Row(
              children: [
                _TypeChip(
                  label: 'Bank',
                  icon: Icons.account_balance_outlined,
                  isSelected: _selectedType == 'bank',
                  onTap: () => setState(() => _selectedType = 'bank'),
                ),
                const SizedBox(width: 8),
                _TypeChip(
                  label: 'E-Wallet',
                  icon: Icons.account_balance_wallet_outlined,
                  isSelected: _selectedType == 'ewallet',
                  onTap: () => setState(() => _selectedType = 'ewallet'),
                ),
                const SizedBox(width: 8),
                _TypeChip(
                  label: 'Cash',
                  icon: Icons.payments_outlined,
                  isSelected: _selectedType == 'cash',
                  onTap: () => setState(() => _selectedType = 'cash'),
                ),
              ],
            ),
            const SizedBox(height: 16),

            // Currency Selector
            const Text(
              'Currency',
              style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: AppColors.darkTextSecondary),
            ),
            const SizedBox(height: 8),
            Row(
              children: [
                _CurrencyChip(
                  currency: 'IDR',
                  label: 'Rupiah (IDR)',
                  isSelected: _selectedCurrency == 'IDR',
                  onTap: () => setState(() => _selectedCurrency = 'IDR'),
                ),
                const SizedBox(width: 8),
                _CurrencyChip(
                  currency: 'MYR',
                  label: 'Ringgit (MYR)',
                  isSelected: _selectedCurrency == 'MYR',
                  onTap: () => setState(() => _selectedCurrency = 'MYR'),
                ),
              ],
            ),
            const SizedBox(height: 16),

            // Initial Balance Field
            TextFormField(
              controller: _initialBalanceController,
              keyboardType: const TextInputType.numberWithOptions(decimal: true),
              style: const TextStyle(
                fontSize: 18,
                fontWeight: FontWeight.w700,
                color: AppColors.darkTextPrimary,
              ),
              decoration: InputDecoration(
                labelText: 'Initial Balance (Starting Nominal)',
                hintText: '0',
                prefixText: _selectedCurrency == 'IDR' ? 'Rp  ' : 'RM  ',
                prefixStyle: const TextStyle(fontSize: 16, fontWeight: FontWeight.w700, color: AppColors.primaryLight),
                labelStyle: const TextStyle(color: AppColors.darkTextSecondary, fontSize: 13),
                hintStyle: const TextStyle(color: AppColors.darkTextMuted, fontSize: 14),
                helperText: 'Enter starting balance for this account (optional)',
                helperStyle: const TextStyle(color: AppColors.darkTextMuted, fontSize: 11),
                filled: true,
                fillColor: Colors.black45,
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(14),
                  borderSide: const BorderSide(color: AppColors.darkCardBorder),
                ),
                focusedBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(14),
                  borderSide: const BorderSide(color: AppColors.primary, width: 1.5),
                ),
              ),
            ),
            const SizedBox(height: 24),

            // Submit Button
            GestureDetector(
              onTap: _isLoading ? null : _submit,
              child: Container(
                height: 50,
                decoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(16),
                  color: AppColors.primary,
                  boxShadow: [
                    BoxShadow(
                      color: AppColors.primary.withValues(alpha: 0.3),
                      blurRadius: 12,
                      offset: const Offset(0, 4),
                    ),
                  ],
                ),
                child: Center(
                  child: _isLoading
                      ? const SizedBox(
                          width: 20,
                          height: 20,
                          child: CircularProgressIndicator(strokeWidth: 2, color: Colors.black),
                        )
                      : const Text(
                          'Save Account',
                          style: TextStyle(fontSize: 15, fontWeight: FontWeight.w700, color: Colors.black),
                        ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _TypeChip extends StatelessWidget {
  const _TypeChip({
    required this.label,
    required this.icon,
    required this.isSelected,
    required this.onTap,
  });

  final String label;
  final IconData icon;
  final bool isSelected;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: GestureDetector(
        onTap: onTap,
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 10),
          decoration: BoxDecoration(
            color: isSelected ? AppColors.primary.withValues(alpha: 0.15) : Colors.black45,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(
              color: isSelected ? AppColors.primary : AppColors.darkCardBorder,
              width: isSelected ? 1.5 : 1,
            ),
          ),
          child: Column(
            children: [
              Icon(icon, size: 18, color: isSelected ? AppColors.primaryLight : AppColors.darkTextSecondary),
              const SizedBox(height: 4),
              Text(
                label,
                style: TextStyle(
                  fontSize: 11,
                  fontWeight: isSelected ? FontWeight.w700 : FontWeight.w500,
                  color: isSelected ? AppColors.darkTextPrimary : AppColors.darkTextSecondary,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _CurrencyChip extends StatelessWidget {
  const _CurrencyChip({
    required this.currency,
    required this.label,
    required this.isSelected,
    required this.onTap,
  });

  final String currency;
  final String label;
  final bool isSelected;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: GestureDetector(
        onTap: onTap,
        child: Container(
          padding: const EdgeInsets.symmetric(vertical: 10),
          decoration: BoxDecoration(
            color: isSelected ? AppColors.primary.withValues(alpha: 0.15) : Colors.black45,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(
              color: isSelected ? AppColors.primary : AppColors.darkCardBorder,
              width: isSelected ? 1.5 : 1,
            ),
          ),
          child: Center(
            child: Text(
              label,
              style: TextStyle(
                fontSize: 12,
                fontWeight: isSelected ? FontWeight.w700 : FontWeight.w500,
                color: isSelected ? AppColors.darkTextPrimary : AppColors.darkTextSecondary,
              ),
            ),
          ),
        ),
      ),
    );
  }
}
