import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/theme/app_colors.dart';
import '../../../core/utils/currency_formatter.dart';
import '../../../core/widgets/app_calendar_sheet.dart';
import '../../../core/widgets/app_dropdown.dart';
import '../../../domain/entities/category.dart';
import '../../../domain/entities/transaction.dart';
import '../../accounts/providers/account_providers.dart';
import '../../categories/providers/category_providers.dart';
import '../../categories/screens/categories_screen.dart';
import '../providers/transaction_providers.dart';

class AddTransactionSheet extends ConsumerStatefulWidget {
  const AddTransactionSheet({super.key, this.transactionToEdit});

  final Transaction? transactionToEdit;

  static Future<void> show(BuildContext context, {Transaction? transactionToEdit}) {
    return showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (_) => AddTransactionSheet(transactionToEdit: transactionToEdit),
    );
  }

  @override
  ConsumerState<AddTransactionSheet> createState() => _AddTransactionSheetState();
}

class _AddTransactionSheetState extends ConsumerState<AddTransactionSheet> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _amountController;
  late final TextEditingController _descController;

  late String _selectedType;
  String _selectedCurrency = 'IDR';
  String? _selectedAccountId;
  Category? _selectedCategory;
  late DateTime _selectedDate;
  bool _isLoading = false;

  bool get isEditing => widget.transactionToEdit != null;

  @override
  void initState() {
    super.initState();
    final editTx = widget.transactionToEdit;
    if (editTx != null) {
      _selectedType = editTx.type;
      _selectedAccountId = editTx.accountId;
      _selectedDate = editTx.transactionDate;
      _amountController = TextEditingController(
        text: CurrencyInputFormatter.format(editTx.amount),
      );
      _descController = TextEditingController(text: editTx.description ?? '');
    } else {
      _selectedType = 'expense';
      _selectedDate = DateTime.now();
      _amountController = TextEditingController();
      _descController = TextEditingController();
    }
  }

  @override
  void dispose() {
    _amountController.dispose();
    _descController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedAccountId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please select a source account'),
          backgroundColor: AppColors.red,
        ),
      );
      return;
    }

    final amount = CurrencyInputFormatter.parse(_amountController.text);
    if (amount <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please enter a valid amount'),
          backgroundColor: AppColors.red,
        ),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      if (isEditing) {
        final updatedTx = widget.transactionToEdit!.copyWith(
          accountId: _selectedAccountId!,
          categoryId: _selectedCategory?.id ?? widget.transactionToEdit!.categoryId,
          type: _selectedType,
          amount: amount,
          description: _descController.text.trim().isEmpty ? null : _descController.text.trim(),
          transactionDate: _selectedDate,
        );

        await updateTransaction(ref, updatedTx);

        if (mounted) {
          Navigator.pop(context);
        }
      } else {
        final newTx = Transaction(
          id: '', // Generated by database
          accountId: _selectedAccountId!,
          categoryId: _selectedCategory?.id,
          type: _selectedType,
          amount: amount,
          description: _descController.text.trim().isEmpty ? null : _descController.text.trim(),
          transactionDate: _selectedDate,
        );

        await createTransaction(ref, newTx);

        if (mounted) {
          Navigator.pop(context);
        }
      }
    } catch (_) {
      // Failed silently / handled
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final bottomInset = MediaQuery.of(context).viewInsets.bottom;
    final accountsAsync = ref.watch(accountsProvider);
    final allCategoriesAsync = ref.watch(categoriesProvider);

    // Auto-resolve category on editing if not already set
    if (isEditing && _selectedCategory == null && widget.transactionToEdit?.categoryId != null) {
      final allCats = allCategoriesAsync.asData?.value;
      if (allCats != null) {
        final match = allCats.where((c) => c.id == widget.transactionToEdit!.categoryId).firstOrNull;
        if (match != null) {
          _selectedCategory = match;
        }
      }
    }

    return Container(
      padding: EdgeInsets.fromLTRB(22, 20, 22, 20 + bottomInset),
      decoration: const BoxDecoration(
        color: AppColors.darkCardBg,
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
        border: Border(top: BorderSide(color: AppColors.darkCardBorder, width: 1.5)),
      ),
      child: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Drag Handle
              Center(
                child: Container(
                  width: 40,
                  height: 4,
                  decoration: BoxDecoration(
                    color: AppColors.darkTextMuted,
                    borderRadius: BorderRadius.circular(2),
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Title
              Text(
                isEditing ? 'Edit Transaction' : 'Record Transaction',
                style: const TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.w700,
                  color: AppColors.darkTextPrimary,
                ),
              ),
              const SizedBox(height: 16),

              // Toggle Type (Expense vs Income)              // Type Switcher
              Container(
                height: 48,
                padding: const EdgeInsets.all(4),
                decoration: BoxDecoration(
                  color: AppColors.darkCardBg,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(color: AppColors.darkCardBorder),
                ),
                child: Row(
                  children: [
                    Expanded(
                      child: _TypeSwitchButton(
                        label: 'Expense',
                        isActive: _selectedType == 'expense',
                        activeColor: AppColors.red,
                        onTap: () => setState(() {
                          _selectedType = 'expense';
                          _selectedCategory = null;
                        }),
                      ),
                    ),
                    Expanded(
                      child: _TypeSwitchButton(
                        label: 'Income',
                        isActive: _selectedType == 'income',
                        activeColor: AppColors.primary,
                        onTap: () => setState(() {
                          _selectedType = 'income';
                          _selectedCategory = null;
                        }),
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 16),

              // Amount & Currency Switcher Row
              accountsAsync.when(
                data: (accounts) => Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Expanded(
                      flex: 3,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'Amount',
                            style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: AppColors.darkTextSecondary),
                          ),
                          const SizedBox(height: 6),
                          TextFormField(
                            controller: _amountController,
                            keyboardType: TextInputType.number,
                            inputFormatters: [CurrencyInputFormatter()],
                            style: const TextStyle(
                              fontSize: 14,
                              fontWeight: FontWeight.w600,
                              color: Colors.white,
                            ),
                            decoration: InputDecoration(
                              hintText: '0',
                              prefixText: _selectedCurrency == 'IDR' ? 'Rp ' : 'RM ',
                              prefixStyle: const TextStyle(fontSize: 14, fontWeight: FontWeight.w700, color: AppColors.primary),
                              hintStyle: const TextStyle(color: AppColors.darkTextMuted, fontSize: 14),
                              filled: true,
                              fillColor: AppColors.darkCardBg,
                              contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                              border: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(16),
                                borderSide: const BorderSide(color: AppColors.darkCardBorder),
                              ),
                              enabledBorder: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(16),
                                borderSide: const BorderSide(color: AppColors.darkCardBorder),
                              ),
                              focusedBorder: OutlineInputBorder(
                                borderRadius: BorderRadius.circular(16),
                                borderSide: const BorderSide(color: AppColors.primary, width: 1.2),
                              ),
                            ),
                            validator: (v) => (v == null || v.trim().isEmpty) ? 'Required' : null,
                          ),
                        ],
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      flex: 2,
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const Text(
                            'Currency',
                            style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: AppColors.darkTextSecondary),
                          ),
                          const SizedBox(height: 6),
                          Container(
                            height: 50,
                            padding: const EdgeInsets.all(4),
                            decoration: BoxDecoration(
                              color: AppColors.darkCardBg,
                              borderRadius: BorderRadius.circular(16),
                              border: Border.all(color: AppColors.darkCardBorder),
                            ),
                            child: Row(
                              children: [
                                Expanded(
                                  child: GestureDetector(
                                    onTap: () {
                                      setState(() {
                                        _selectedCurrency = 'IDR';
                                        final match = accounts.where((a) => a.currency == 'IDR').firstOrNull;
                                        if (match != null) _selectedAccountId = match.id;
                                      });
                                    },
                                    child: Container(
                                      decoration: BoxDecoration(
                                        color: _selectedCurrency == 'IDR' ? AppColors.primary : Colors.transparent,
                                        borderRadius: BorderRadius.circular(12),
                                      ),
                                      alignment: Alignment.center,
                                      child: Text(
                                        'IDR',
                                        style: TextStyle(
                                          fontSize: 12,
                                          fontWeight: FontWeight.w700,
                                          color: _selectedCurrency == 'IDR' ? Colors.black : AppColors.darkTextSecondary,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                                Expanded(
                                  child: GestureDetector(
                                    onTap: () {
                                      setState(() {
                                        _selectedCurrency = 'MYR';
                                        final match = accounts.where((a) => a.currency == 'MYR').firstOrNull;
                                        if (match != null) _selectedAccountId = match.id;
                                      });
                                    },
                                    child: Container(
                                      decoration: BoxDecoration(
                                        color: _selectedCurrency == 'MYR' ? AppColors.primary : Colors.transparent,
                                        borderRadius: BorderRadius.circular(12),
                                      ),
                                      alignment: Alignment.center,
                                      child: Text(
                                        'MYR',
                                        style: TextStyle(
                                          fontSize: 12,
                                          fontWeight: FontWeight.w700,
                                          color: _selectedCurrency == 'MYR' ? Colors.black : AppColors.darkTextSecondary,
                                        ),
                                      ),
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                ),
                loading: () => const SizedBox.shrink(),
                error: (_, _) => const SizedBox.shrink(),
              ),
              const SizedBox(height: 16),

              // Account Selector Dropdown
              accountsAsync.when(
                data: (accounts) {
                  if (accounts.isEmpty) {
                    return const Text('No active accounts found.', style: TextStyle(color: AppColors.orange));
                  }
                  
                  // Initialize or validate selected account
                  if (_selectedAccountId == null || !accounts.any((a) => a.id == _selectedAccountId)) {
                    final match = accounts.where((a) => a.currency == _selectedCurrency).firstOrNull;
                    _selectedAccountId = match?.id ?? accounts.first.id;
                    final currentAcc = accounts.firstWhere((a) => a.id == _selectedAccountId);
                    _selectedCurrency = currentAcc.currency;
                  }

                  return AppDropdownFormField<String>(
                    initialValue: _selectedAccountId,
                    labelText: 'Source Account',
                    items: accounts.map((acc) {
                      return AppDropdownItem<String>(
                        value: acc.id,
                        label: '${acc.name} (${acc.currency})',
                        subtitle: 'Type: ${acc.type.toUpperCase()}',
                        icon: Icon(
                          acc.type == 'bank'
                              ? Icons.account_balance_outlined
                              : acc.type == 'ewallet'
                                  ? Icons.account_balance_wallet_outlined
                                  : Icons.payments_outlined,
                          size: 20,
                          color: AppColors.primary,
                        ),
                      );
                    }).toList(),
                    onChanged: (val) {
                      if (val != null) {
                        setState(() {
                          _selectedAccountId = val;
                          final acc = accounts.where((a) => a.id == val).firstOrNull;
                          if (acc != null) {
                            _selectedCurrency = acc.currency;
                          }
                        });
                      }
                    },
                  );
                },
                loading: () => const LinearProgressIndicator(),
                error: (e, _) => Text('$e', style: const TextStyle(color: AppColors.red)),
              ),
              const SizedBox(height: 16),

              // Category Selector
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    'Category (Optional)',
                    style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: AppColors.darkTextSecondary),
                  ),
                  const SizedBox(height: 6),
                  InkWell(
                    borderRadius: BorderRadius.circular(16),
                    onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (_) => CategoriesScreen(
                            pickerMode: true,
                            initialType: _selectedType,
                            onSelect: (cat) => setState(() => _selectedCategory = cat),
                          ),
                        ),
                      );
                    },
                    child: Container(
                      height: 50,
                      padding: const EdgeInsets.symmetric(horizontal: 16),
                      decoration: BoxDecoration(
                        color: AppColors.darkCardBg,
                        borderRadius: BorderRadius.circular(16),
                        border: Border.all(color: AppColors.darkCardBorder),
                      ),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Row(
                            children: [
                              Container(
                                width: 28,
                                height: 28,
                                decoration: BoxDecoration(
                                  shape: BoxShape.circle,
                                  color: _selectedCategory != null
                                      ? AppColors.primary.withValues(alpha: 0.15)
                                      : Colors.white.withValues(alpha: 0.06),
                                ),
                                child: Icon(
                                  _selectedCategory != null
                                      ? _getCategoryIcon(_selectedCategory!.icon)
                                      : Icons.category_outlined,
                                  size: 15,
                                  color: _selectedCategory != null ? AppColors.primaryLight : AppColors.darkTextSecondary,
                                ),
                              ),
                              const SizedBox(width: 10),
                              Text(
                                _selectedCategory?.name ?? 'Select Category',
                                style: TextStyle(
                                  fontSize: 14,
                                  fontWeight: _selectedCategory != null ? FontWeight.w600 : FontWeight.w500,
                                  color: _selectedCategory != null ? Colors.white : AppColors.darkTextMuted,
                                ),
                              ),
                            ],
                          ),
                          Row(
                            children: [
                              if (_selectedCategory != null)
                                GestureDetector(
                                  onTap: () => setState(() => _selectedCategory = null),
                                  child: Container(
                                    padding: const EdgeInsets.all(4),
                                    margin: const EdgeInsets.only(right: 6),
                                    decoration: const BoxDecoration(
                                      shape: BoxShape.circle,
                                      color: Colors.black38,
                                    ),
                                    child: const Icon(Icons.close_rounded, size: 14, color: AppColors.darkTextSecondary),
                                  ),
                                ),
                              const Icon(Icons.chevron_right_rounded, size: 18, color: AppColors.darkTextSecondary),
                            ],
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              // Date Picker
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    'Transaction Date',
                    style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: AppColors.darkTextSecondary),
                  ),
                  const SizedBox(height: 6),
                  InkWell(
                    borderRadius: BorderRadius.circular(16),
                    onTap: () async {
                      final picked = await AppDatePickerSheet.show(
                        context,
                        initialDate: _selectedDate,
                        firstDate: DateTime(2020),
                        lastDate: DateTime(2035),
                      );
                      if (picked != null) {
                        setState(() => _selectedDate = picked);
                      }
                    },
                    child: Container(
                      height: 50,
                      padding: const EdgeInsets.symmetric(horizontal: 16),
                      decoration: BoxDecoration(
                        color: AppColors.darkCardBg,
                        borderRadius: BorderRadius.circular(16),
                        border: Border.all(color: AppColors.darkCardBorder),
                      ),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Row(
                            children: [
                              const Icon(Icons.calendar_month_rounded, size: 18, color: AppColors.primaryLight),
                              const SizedBox(width: 10),
                              Text(
                                '${_selectedDate.day}/${_selectedDate.month}/${_selectedDate.year}',
                                style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w500, color: Colors.white),
                              ),
                            ],
                          ),
                          const Icon(Icons.chevron_right_rounded, size: 18, color: AppColors.darkTextSecondary),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              // Description field
              Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    'Description / Notes (Optional)',
                    style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: AppColors.darkTextSecondary),
                  ),
                  const SizedBox(height: 6),
                  TextFormField(
                    controller: _descController,
                    style: const TextStyle(color: Colors.white, fontSize: 14, fontWeight: FontWeight.w600),
                    decoration: InputDecoration(
                      hintText: 'e.g., Lunch with friends, groceries, wifi',
                      hintStyle: const TextStyle(color: AppColors.darkTextMuted, fontSize: 14),
                      filled: true,
                      fillColor: AppColors.darkCardBg,
                      contentPadding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(16),
                        borderSide: const BorderSide(color: AppColors.darkCardBorder),
                      ),
                      enabledBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(16),
                        borderSide: const BorderSide(color: AppColors.darkCardBorder),
                      ),
                      focusedBorder: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(16),
                        borderSide: const BorderSide(color: AppColors.primary, width: 1.2),
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 24),

              // Submit Button
              SizedBox(
                width: double.infinity,
                height: 50,
                child: ElevatedButton(
                  style: ElevatedButton.styleFrom(
                    backgroundColor: AppColors.primary,
                    foregroundColor: Colors.black,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                    elevation: 0,
                  ),
                  onPressed: _isLoading ? null : _submit,
                  child: _isLoading
                      ? const SizedBox(
                          width: 20,
                          height: 20,
                          child: CircularProgressIndicator(strokeWidth: 2, color: Colors.black),
                        )
                      : Text(
                          isEditing ? 'Update Transaction' : 'Save Transaction',
                          style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w800),
                        ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  IconData _getCategoryIcon(String? iconName) {
    switch (iconName) {
      case 'restaurant':
        return Icons.restaurant_rounded;
      case 'directions_car':
        return Icons.directions_car_rounded;
      case 'shopping_bag':
        return Icons.shopping_bag_rounded;
      case 'medical_services':
        return Icons.medical_services_rounded;
      case 'bolt':
        return Icons.bolt_rounded;
      case 'movie':
        return Icons.movie_rounded;
      case 'payments':
        return Icons.payments_rounded;
      case 'card_giftcard':
        return Icons.card_giftcard_rounded;
      case 'savings':
        return Icons.savings_rounded;
      default:
        return Icons.category_rounded;
    }
  }
}

class _TypeSwitchButton extends StatelessWidget {
  const _TypeSwitchButton({
    required this.label,
    required this.isActive,
    required this.activeColor,
    required this.onTap,
  });

  final String label;
  final bool isActive;
  final Color activeColor;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 180),
        padding: const EdgeInsets.symmetric(vertical: 10),
        decoration: BoxDecoration(
          color: isActive ? activeColor : Colors.transparent,
          borderRadius: BorderRadius.circular(12),
        ),
        child: Center(
          child: Text(
            label,
            style: TextStyle(
              fontSize: 13,
              fontWeight: FontWeight.w700,
              color: isActive ? Colors.black : AppColors.darkTextSecondary,
            ),
          ),
        ),
      ),
    );
  }
}
