import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../core/theme/app_colors.dart';
import '../../../domain/entities/category.dart';
import '../../../domain/entities/transaction.dart';
import '../../accounts/providers/account_providers.dart';
import '../../categories/providers/category_providers.dart';
import '../../categories/screens/categories_screen.dart';
import '../providers/transaction_providers.dart';

class AddTransactionSheet extends ConsumerStatefulWidget {
  const AddTransactionSheet({super.key, this.transactionToEdit});

  final Transaction? transactionToEdit;

  static Future<void> show(BuildContext context, {Transaction? transactionToEdit}) {
    return showModalBottomSheet(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (_) => AddTransactionSheet(transactionToEdit: transactionToEdit),
    );
  }

  @override
  ConsumerState<AddTransactionSheet> createState() => _AddTransactionSheetState();
}

class _AddTransactionSheetState extends ConsumerState<AddTransactionSheet> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _amountController;
  late final TextEditingController _descController;

  late String _selectedType;
  String _selectedCurrency = 'IDR';
  String? _selectedAccountId;
  Category? _selectedCategory;
  late DateTime _selectedDate;
  bool _isLoading = false;

  bool get isEditing => widget.transactionToEdit != null;

  @override
  void initState() {
    super.initState();
    final editTx = widget.transactionToEdit;
    if (editTx != null) {
      _selectedType = editTx.type;
      _selectedAccountId = editTx.accountId;
      _selectedDate = editTx.transactionDate;
      _amountController = TextEditingController(
        text: editTx.amount % 1 == 0
            ? editTx.amount.toStringAsFixed(0)
            : editTx.amount.toString(),
      );
      _descController = TextEditingController(text: editTx.description ?? '');
    } else {
      _selectedType = 'expense';
      _selectedDate = DateTime.now();
      _amountController = TextEditingController();
      _descController = TextEditingController();
    }
  }

  @override
  void dispose() {
    _amountController.dispose();
    _descController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedAccountId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please select a source account'),
          backgroundColor: AppColors.red,
        ),
      );
      return;
    }

    final rawAmount = _amountController.text.replaceAll(RegExp(r'[^0-9.]'), '');
    final amount = num.tryParse(rawAmount);
    if (amount == null || amount <= 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please enter a valid amount'),
          backgroundColor: AppColors.red,
        ),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      if (isEditing) {
        final updatedTx = widget.transactionToEdit!.copyWith(
          accountId: _selectedAccountId!,
          categoryId: _selectedCategory?.id ?? widget.transactionToEdit!.categoryId,
          type: _selectedType,
          amount: amount,
          description: _descController.text.trim().isEmpty ? null : _descController.text.trim(),
          transactionDate: _selectedDate,
        );

        await updateTransaction(ref, updatedTx);

        if (mounted) {
          Navigator.pop(context);
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Transaction updated successfully!'),
              backgroundColor: AppColors.primary,
            ),
          );
        }
      } else {
        final newTx = Transaction(
          id: '', // Generated by database
          accountId: _selectedAccountId!,
          categoryId: _selectedCategory?.id,
          type: _selectedType,
          amount: amount,
          description: _descController.text.trim().isEmpty ? null : _descController.text.trim(),
          transactionDate: _selectedDate,
        );

        await createTransaction(ref, newTx);

        if (mounted) {
          Navigator.pop(context);
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Transaction recorded successfully!'),
              backgroundColor: AppColors.primary,
            ),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to save transaction: $e'),
            backgroundColor: AppColors.red,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final bottomInset = MediaQuery.of(context).viewInsets.bottom;
    final accountsAsync = ref.watch(accountsProvider);
    final categoriesAsync = ref.watch(categoriesByTypeProvider(_selectedType));

    return Container(
      padding: EdgeInsets.fromLTRB(22, 20, 22, 20 + bottomInset),
      decoration: const BoxDecoration(
        color: AppColors.darkCardBg,
        borderRadius: BorderRadius.vertical(top: Radius.circular(28)),
        border: Border(top: BorderSide(color: AppColors.darkCardBorder, width: 1.5)),
      ),
      child: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Drag Handle
              Center(
                child: Container(
                  width: 40,
                  height: 4,
                  decoration: BoxDecoration(
                    color: AppColors.darkTextMuted,
                    borderRadius: BorderRadius.circular(2),
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // Title
              Text(
                isEditing ? 'Edit Transaction' : 'Record Transaction',
                style: const TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.w700,
                  color: AppColors.darkTextPrimary,
                ),
              ),
              const SizedBox(height: 16),

              // Toggle Type (Expense vs Income)
              Container(
                padding: const EdgeInsets.all(4),
                decoration: BoxDecoration(
                  color: Colors.black54,
                  borderRadius: BorderRadius.circular(16),
                  border: Border.all(color: AppColors.darkCardBorder),
                ),
                child: Row(
                  children: [
                    Expanded(
                      child: _TypeSwitchButton(
                        label: 'Expense',
                        isActive: _selectedType == 'expense',
                        activeColor: AppColors.red,
                        onTap: () => setState(() {
                          _selectedType = 'expense';
                          _selectedCategory = null;
                        }),
                      ),
                    ),
                    Expanded(
                      child: _TypeSwitchButton(
                        label: 'Income',
                        isActive: _selectedType == 'income',
                        activeColor: AppColors.primary,
                        onTap: () => setState(() {
                          _selectedType = 'income';
                          _selectedCategory = null;
                        }),
                      ),
                    ),
                  ],
                ),
              ),
              const SizedBox(height: 16),

              // Currency Selector (IDR / MYR)
              const Text(
                'Currency',
                style: TextStyle(fontSize: 12, fontWeight: FontWeight.w600, color: AppColors.darkTextSecondary),
              ),
              const SizedBox(height: 8),
              accountsAsync.when(
                data: (accounts) => Row(
                  children: [
                    Expanded(
                      child: _CurrencyChip(
                        currency: 'IDR',
                        label: 'Rupiah (IDR \u00b7 Rp)',
                        isSelected: _selectedCurrency == 'IDR',
                        onTap: () {
                          setState(() {
                            _selectedCurrency = 'IDR';
                            final match = accounts.where((a) => a.currency == 'IDR').firstOrNull;
                            if (match != null) {
                              _selectedAccountId = match.id;
                            }
                          });
                        },
                      ),
                    ),
                    const SizedBox(width: 8),
                    Expanded(
                      child: _CurrencyChip(
                        currency: 'MYR',
                        label: 'Ringgit (MYR \u00b7 RM)',
                        isSelected: _selectedCurrency == 'MYR',
                        onTap: () {
                          setState(() {
                            _selectedCurrency = 'MYR';
                            final match = accounts.where((a) => a.currency == 'MYR').firstOrNull;
                            if (match != null) {
                              _selectedAccountId = match.id;
                            }
                          });
                        },
                      ),
                    ),
                  ],
                ),
                loading: () => const SizedBox.shrink(),
                error: (_, _) => const SizedBox.shrink(),
              ),
              const SizedBox(height: 16),

              // Amount Input
              TextFormField(
                controller: _amountController,
                keyboardType: const TextInputType.numberWithOptions(decimal: true),
                style: const TextStyle(
                  fontSize: 22,
                  fontWeight: FontWeight.w700,
                  color: AppColors.darkTextPrimary,
                ),
                decoration: InputDecoration(
                  labelText: 'Amount (${_selectedCurrency == 'IDR' ? 'Rp' : 'RM'})',
                  hintText: '0',
                  prefixText: _selectedCurrency == 'IDR' ? 'Rp  ' : 'RM  ',
                  prefixStyle: const TextStyle(fontSize: 18, fontWeight: FontWeight.w700, color: AppColors.primaryLight),
                  labelStyle: const TextStyle(color: AppColors.darkTextSecondary, fontSize: 13),
                  filled: true,
                  fillColor: Colors.black45,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(14),
                    borderSide: const BorderSide(color: AppColors.darkCardBorder),
                  ),
                  focusedBorder: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(14),
                    borderSide: const BorderSide(color: AppColors.primary, width: 1.5),
                  ),
                ),
                validator: (v) => (v == null || v.trim().isEmpty) ? 'Amount is required' : null,
              ),
              const SizedBox(height: 14),

              // Account Selector Dropdown
              accountsAsync.when(
                data: (accounts) {
                  if (accounts.isEmpty) {
                    return const Text('No active accounts found.', style: TextStyle(color: AppColors.orange));
                  }
                  
                  // Initialize or validate selected account
                  if (_selectedAccountId == null || !accounts.any((a) => a.id == _selectedAccountId)) {
                    final match = accounts.where((a) => a.currency == _selectedCurrency).firstOrNull;
                    _selectedAccountId = match?.id ?? accounts.first.id;
                    final currentAcc = accounts.firstWhere((a) => a.id == _selectedAccountId);
                    _selectedCurrency = currentAcc.currency;
                  }

                  return DropdownButtonFormField<String>(
                    initialValue: _selectedAccountId,
                    dropdownColor: AppColors.darkCardBg,
                    style: const TextStyle(color: AppColors.darkTextPrimary, fontSize: 14),
                    decoration: InputDecoration(
                      labelText: 'Source Account',
                      labelStyle: const TextStyle(color: AppColors.darkTextSecondary, fontSize: 13),
                      filled: true,
                      fillColor: Colors.black45,
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(14),
                        borderSide: const BorderSide(color: AppColors.darkCardBorder),
                      ),
                    ),
                    items: accounts.map((acc) {
                      return DropdownMenuItem(
                        value: acc.id,
                        child: Text('${acc.name} (${acc.currency})'),
                      );
                    }).toList(),
                    onChanged: (val) {
                      if (val != null) {
                        setState(() {
                          _selectedAccountId = val;
                          final acc = accounts.where((a) => a.id == val).firstOrNull;
                          if (acc != null) {
                            _selectedCurrency = acc.currency;
                          }
                        });
                      }
                    },
                  );
                },
                loading: () => const LinearProgressIndicator(),
                error: (e, _) => Text('$e', style: const TextStyle(color: AppColors.red)),
              ),
              const SizedBox(height: 14),

              // Category Selector
              categoriesAsync.when(
                data: (categories) {
                  return InkWell(
                    onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (_) => CategoriesScreen(
                            pickerMode: true,
                            onSelect: (cat) => setState(() => _selectedCategory = cat),
                          ),
                        ),
                      );
                    },
                    child: Container(
                      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 14),
                      decoration: BoxDecoration(
                        color: Colors.black45,
                        borderRadius: BorderRadius.circular(14),
                        border: Border.all(color: AppColors.darkCardBorder),
                      ),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Row(
                            children: [
                              const Icon(Icons.category_outlined, size: 20, color: AppColors.darkTextSecondary),
                              const SizedBox(width: 10),
                              Text(
                                _selectedCategory?.name ?? 'Select Category (Optional)',
                                style: TextStyle(
                                  fontSize: 14,
                                  color: _selectedCategory != null ? Colors.white : AppColors.darkTextSecondary,
                                ),
                              ),
                            ],
                          ),
                          const Icon(Icons.chevron_right_rounded, size: 20, color: AppColors.darkTextSecondary),
                        ],
                      ),
                    ),
                  );
                },
                loading: () => const SizedBox.shrink(),
                error: (_, _) => const SizedBox.shrink(),
              ),
              const SizedBox(height: 14),

              // Date Picker
              InkWell(
                onTap: () async {
                  final picked = await showDatePicker(
                    context: context,
                    initialDate: _selectedDate,
                    firstDate: DateTime(2020),
                    lastDate: DateTime(2030),
                  );
                  if (picked != null) {
                    setState(() => _selectedDate = picked);
                  }
                },
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 14),
                  decoration: BoxDecoration(
                    color: Colors.black45,
                    borderRadius: BorderRadius.circular(14),
                    border: Border.all(color: AppColors.darkCardBorder),
                  ),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: [
                      Row(
                        children: [
                          const Icon(Icons.calendar_today_rounded, size: 18, color: AppColors.darkTextSecondary),
                          const SizedBox(width: 10),
                          Text(
                            'Date: ${_selectedDate.day}/${_selectedDate.month}/${_selectedDate.year}',
                            style: const TextStyle(fontSize: 14, color: AppColors.darkTextPrimary),
                          ),
                        ],
                      ),
                      const Icon(Icons.edit_calendar_rounded, size: 18, color: AppColors.primaryLight),
                    ],
                  ),
                ),
              ),
              const SizedBox(height: 14),

              // Description field
              TextFormField(
                controller: _descController,
                style: const TextStyle(color: AppColors.darkTextPrimary, fontSize: 14),
                decoration: InputDecoration(
                  labelText: 'Description / Notes (Optional)',
                  hintText: 'e.g., Lunch with friends, groceries, wifi',
                  labelStyle: const TextStyle(color: AppColors.darkTextSecondary, fontSize: 13),
                  hintStyle: const TextStyle(color: AppColors.darkTextMuted, fontSize: 12),
                  filled: true,
                  fillColor: Colors.black45,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(14),
                    borderSide: const BorderSide(color: AppColors.darkCardBorder),
                  ),
                ),
              ),
              const SizedBox(height: 22),

              // Submit Button
              GestureDetector(
                onTap: _isLoading ? null : _submit,
                child: Container(
                  height: 50,
                  decoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(16),
                    color: AppColors.primary,
                    boxShadow: [
                      BoxShadow(
                        color: AppColors.primary.withValues(alpha: 0.3),
                        blurRadius: 12,
                        offset: const Offset(0, 4),
                      ),
                    ],
                  ),
                  child: Center(
                    child: _isLoading
                        ? const SizedBox(
                            width: 20,
                            height: 20,
                            child: CircularProgressIndicator(strokeWidth: 2, color: Colors.black),
                          )
                        : Text(
                            isEditing ? 'Update Transaction' : 'Save Transaction',
                            style: const TextStyle(fontSize: 15, fontWeight: FontWeight.w700, color: Colors.black),
                          ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _TypeSwitchButton extends StatelessWidget {
  const _TypeSwitchButton({
    required this.label,
    required this.isActive,
    required this.activeColor,
    required this.onTap,
  });

  final String label;
  final bool isActive;
  final Color activeColor;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 180),
        padding: const EdgeInsets.symmetric(vertical: 10),
        decoration: BoxDecoration(
          color: isActive ? activeColor : Colors.transparent,
          borderRadius: BorderRadius.circular(12),
        ),
        child: Center(
          child: Text(
            label,
            style: TextStyle(
              fontSize: 13,
              fontWeight: FontWeight.w700,
              color: isActive ? Colors.black : AppColors.darkTextSecondary,
            ),
          ),
        ),
      ),
    );
  }
}

class _CurrencyChip extends StatelessWidget {
  const _CurrencyChip({
    required this.currency,
    required this.label,
    required this.isSelected,
    required this.onTap,
  });

  final String currency;
  final String label;
  final bool isSelected;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: onTap,
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 180),
        padding: const EdgeInsets.symmetric(vertical: 10),
        decoration: BoxDecoration(
          color: isSelected ? AppColors.primary.withValues(alpha: 0.18) : Colors.black45,
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
            color: isSelected ? AppColors.primary : AppColors.darkCardBorder,
            width: isSelected ? 1.5 : 1,
          ),
        ),
        child: Center(
          child: Text(
            label,
            style: TextStyle(
              fontSize: 12,
              fontWeight: isSelected ? FontWeight.w700 : FontWeight.w500,
              color: isSelected ? AppColors.darkTextPrimary : AppColors.darkTextSecondary,
            ),
          ),
        ),
      ),
    );
  }
}
